version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: meli_case
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: ./airflow/docker/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/meli_case
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.auth.backend.password
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/pipeline:/opt/airflow/pipeline
      - ./airflow/data:/opt/airflow/data
    depends_on:
      - postgres
    command: webserver
    ports:
      - "8080:8080"

  scheduler:
    build:
      context: .
      dockerfile: ./airflow/docker/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/meli_case
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.auth.backend.password
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/pipeline:/opt/airflow/pipeline
      - ./airflow/data:/opt/airflow/data
    depends_on:
      - postgres
    command: scheduler

volumes:
  pgdata:
